#!/usr/bin/env python

import couchdb
import time

from configobj import ConfigObj
from twisted.web import server, resource
from twisted.internet import reactor


def getConfig():
    cfgFile = file('config.cfg')
    return ConfigObj(cfgFile)


class LUSDResource(resource.Resource):
    """
    Resource handling all HTTP requests to the short url daemon.
    GET requests are redirected to the appropriate long url.
    POST requests return a short url to a given long one.
    """
    
    isLeaf = True

    def getLocation(self, _id):
        couch = couchdb.Server(config['couchdb_server'])
        db    = couch[config['couchdb_database']]
        try:
            doc = db[_id]
            
            # Update stats
            doc['hits']        = doc['hits'] + 1
            doc['last_access'] = time.asctime(time.localtime(time.time()))
            db[_id] = doc
            
            return doc['location']
        except couchdb.http.ResourceNotFound:
            print("Resource " + _id + " not found")
            return None
    
    def render_GET(self, request):
        location = self.getLocation(request.path[1:])
        
        if location == None:
            request.setResponseCode(404)
            return "404 not found"
        else:
            request.setResponseCode(301)
            request.setHeader("location", location)
            return "301 moved permanently to " + location
            
    def render_POST(self, request):
        return


config = getConfig()
reactor.listenTCP(int(config['listen_port']), server.Site(LUSDResource()))
reactor.run()
