#!/usr/bin/env python

#  Little URL Shortening Daemon (lusd)
#  Copyright (C) 2013 Christian Lins <christian@lins.me>
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import couchdb
import os
import time

from configobj import ConfigObj
from twisted.web import server, resource, static
from twisted.internet import reactor

# Short url alphabet, note the missing l and I for better readability
ALPHABET = '0123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ'


def getConfig():
    cfgFile = file('config.cfg')
    return ConfigObj(cfgFile)


def shortMe(num):
    out = ''

    while num > 0:
        rem = num % len(ALPHABET)
        num = num / len(ALPHABET)
        out = ALPHABET[rem] + out

    return out


class LUSDResource(resource.Resource):
    """
    Resource handling all HTTP requests to the short url daemon.
    GET requests are redirected to the appropriate long url.
    POST requests return a short url to a given long one.
    """
    
    def getChild(self, path, request):
        return self
    

    def createShortURL(self, longURL):
        couch = couchdb.Server(config['couchdb_server'])
        db    = couch[config['couchdb_database']]

        try:
            doc = db['stats_']
        except couchdb.http.ResourceNotFound:
            doc = {'nextID':1}
            db['status_'] = doc

        # Retrieve and increment nextID
        nextID = int(doc['nextID'])
        doc['nextID'] = nextID + 1
        db['status_'] = doc

        shortID = shortMe(nextID)
        shortDoc = {'_id': shortID, 'hits': '0', 'last_access': '0', 'location': longURL}
        db[shortID] = shortDoc
        
        return config['base_url'] + config['short_prefix'] + shortID


    def getLocation(self, _id):
        if _id == None or _id == '' or _id[0:1] != config['short_prefix']:
            return None

        _id = _id[1:]
        print("Resource " + _id)

        try:            
            couch = couchdb.Server(config['couchdb_server'])
            db    = couch[config['couchdb_database']]
        except couchdb.http.ResourceNotFound:
            print("Wake up! Database setup not valid!")
            os._exit(1)

        try:
            doc = db[_id]
            
            # Update stats
            doc['hits']        = int(doc['hits']) + 1
            doc['last_access'] = time.asctime(time.localtime(time.time()))
            db[_id] = doc
            
            return doc['location']
        except couchdb.http.ResourceNotFound:
            print("Resource " + _id + " not found")
            return None

    
    def render_GET(self, request):
        if request.path == '/create':
            if 'longurl' in request.args:
                return self.createShortURL(request.args['longurl'][0])
            else:
                request.setResponseCode(400)
                return 'Bad Request: missing parameter longurl'
        elif request.path[1:2] == config['short_prefix']:
            location = self.getLocation(request.path[1:])
            
            if location == None:
                if config['error404_redirect'] == 'None':
                    request.setResponseCode(404)
                    return '404 not found'
                else:
                    location = config['error404_redirect'] + request.path[1:]
            
            request.redirect(bytearray(location, encoding='utf-8', errors='replace'))
            return 'Redirecting...'
        else:
            if config['error404_redirect'] == 'None':
                request.setResponseCode(404)
                return '404 not found'
            else:
                location = config['error404_redirect'] + request.path[1:]
                request.redirect(bytearray(location, encoding='utf-8', errors='replace'))
                return 'Redirecting...'


if __name__ == '__main__':
    config = getConfig()

    lusd = LUSDResource()
    lusd.putChild('static', static.File('./static'))
    reactor.listenTCP(int(config['listen_port']), server.Site(lusd))
    reactor.run()
